kind: pipeline
name: default

steps:
  
- name: Deploy
  image: alpine
  environment:
    TF_VAR_auth_token:
      from_secret: TF_VAR_auth_token
    TF_VAR_count_x86:
      from_secret: TF_VAR_count_x86
    TF_VAR_count_arm:
      from_secret: TF_VAR_count_arm
    TF_VAR_project_id:
      from_secret: TF_VAR_project_id
    TF_VAR_cluster_name:
      from_secret: TF_VAR_cluster_name
    PUB_KEY:
      from_secret: public_key_ci_user
    PRIV_KEY:
      from_secret: private_key_ci_user
  commands:
  - echo $PUB_KEY | tee -a packet.pub
  - echo $PRIV_KEY | tee -a packet
  - export TF_VAR_ssh_private_key_path=packet
  - apk --update add curl openssh openssh-client
  - curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip"
  - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
  - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
  - terraform -v
  - terraform init 
  - terraform validate
  - export TF_VAR_control_plane_node_count="0"
  - terraform apply -auto-approve
  - terraform destroy -auto-approve
  # - export TF_VAR_control_plane_node_count="1"
  # - terraform apply -auto-approve
  # - terraform destroy -auto-approve
